### ISSUE TITLE
Update to Nivo-Slider 3.2

### ISSUE THREAD

**Issue by chris246** [YAG-Gallery/yag_themepack_jquery#4]
The currently used version 3.1 still uses jQuery .live() and therefore breaks when newer jQuery versions are used.

**Comment by daniellienert** [comment]
Hey chris246 - thanks for pointing that out! Just update the library and file a pull request. I will be happy to merge it!

**Comment by chris246** [comment]
Hi Daniel, unfortunately it took some time. I've created the pull request fixing this issue and an other one, regarding absRefPrefix support.

**Comment by chris246** [comment]
Hi Daniel,
I wanted to ask about the open pull request.
It would be great, if you could merge it.

**Comment by chris246** [comment]
Thanks
